export type CloudFrontLogPayload = {
  /** Precise floating-point Unix Epoch Timestamp (e.g., 1787984000.123) */
  timestamp: number;
  
  /** The total elapsed time taken to respond in seconds, down to the millisecond */
  time_taken: number;
  
  /** The 3-digit numeric HTTP response code returned to the client */
  sc_status: number;
  
  /** The domain name that the client used to access your asset */
  ctx_host: string;
  
  /** The standardized HTTP request method utilized */
  cs_method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'OPTIONS' | 'HEAD' | 'PATCH';
  
  /** The path to the specific asset being requested */
  cs_uri_stem: string;
  
  /** The portion of the URL following the '?' character. Returns '-' if empty */
  cs_uri_query: string;
  
  /** How the edge server handled the request relative to its local cache */
  x_edge_result_type: 'Hit' | 'Miss' | 'RefreshHit' | 'Redirect' | 'Error' | 'LimitExceeded' | 'CapacityExceeded';
  
  /** A unique, encrypted string token identifier generated by CloudFront for tracing */
  x_edge_request_id: string;
  
  /** The specific cryptographic protocol version used to secure the connection */
  ssl_protocol: 'TLSv1.2' | 'TLSv1.3' | '-';
  
  /** The exact mathematical encryption algorithm cipher suite utilized */
  ssl_cipher: string;
  
  /** The cache classification status that CloudFront sent back to the viewer */
  x_edge_response_result_type: 'Hit' | 'Miss' | 'RefreshHit' | 'Redirect' | 'Error' | 'LimitExceeded' | 'CapacityExceeded';
  
  /** Text string identifying the client's browser engine, device, and OS */
  cs_user_agent: string;
  
  /** The URL of the previous web page that linked the user to this asset */
  cs_referer: string;
  
  /** Name-value cookie string parameters included in the request headers */
  cs_cookie: string;
  
  /** The exact total number of bytes served to the client, headers included */
  sc_bytes: number;
  
  /** The total number of bytes received from the client */
  cs_bytes: number;
  
  /** The specific AWS edge server facility code handling the request (e.g., 'LHR5') */
  x_edge_location: string;
  
  /** The file size in bytes declared in the response payload content-length header */
  sc_content_len: number;
  
  /** Speed of initial response: time between receiving a request and sending the first byte */
  time_to_first_byte: number;
  
  /** The strict value found inside the client's HTTP Host header string */
  cs_host_header: string;
  
  /** The underlying transfer protocol web scheme used */
  cs_protocol: 'http' | 'https' | 'ws' | 'wss';
  
  /** The exact version of the HTTP engine utilized by the client connection */
  cs_protocol_version: 'HTTP/1.0' | 'HTTP/1.1' | 'HTTP/2' | 'HTTP/3';
  
  /** Tracks the processing state if executing Field-Level Encryption */
  fle_status: string;
  
  /** The actual running count of individual body fields encrypted by CloudFront */
  fle_encrypted_fields: number;
  
}

export const columnTitles = [
  // Time and location
  "Datetime",
  "Edge Location",
  // Cliet details
  "User Agent",
  // Request attributes
  "Host Domain",
  "Host Domain Header",
  "URL Path",
  "URL Query String",
  "HTTP Method",
  "Cookie Header",
  "Referrer URL",
  // Response
  "HTTP Status Code",
  "Response Content Length",
  "Bytes Sent",
  "Bytes Received",
  // CDN
  "Edge Cache Result Type",
  "Edge Response Result Type",
  "Edge Detailed Result Type",
  "Edge Request ID",
  "Time Taken (Seconds)",
  "Time to First Byte (Seconds)",
  // Security
  "Protocol Used",
  "HTTP Protocol Version",
  "SSL Protocol Version",
  "SSL Cipher Suite",
  "Field-Level Encryption Status",
  "Field-Level Encryption Count",
]

/**
 * SSE Event containing an actual CloudFront log entry.
 */
type LogEntryEvent = {
  /** Unique identifier for the SSE message event. */
  id?: string;
  /** The type of event being sent. */
  event: 'log_entry';
  /** The log data payload. */
  data: CloudFrontLogPayload;
}

/**
 * SSE Event used to keep the connection alive (Heartbeat).
 */
type PingEvent = {
  id?: string;
  event: 'ping';
  /** Ping events typically have an empty string or timestamp as data. */
  data: string;
}

/**
 * The unified event type received from the CloudFront log stream.
 */
export type CloudFrontLogEvent = LogEntryEvent | PingEvent;
