export const methods = ['GET' , 'POST' , 'PUT' , 'DELETE' , 'OPTIONS' , 'HEAD' , 'PATCH'] as const
export const edgeResultTypes = ['Hit' , 'Miss' , 'RefreshHit' , 'Redirect' , 'Error' , 'LimitExceeded' , 'CapacityExceeded'] as const
export const sslProtocols = ['TLSv1.2' , 'TLSv1.3' , '-'] as const
export const userProtocols = ['http' , 'https' , 'ws' , 'wss'] as const
export const userProtocolVersion = ['HTTP/1.0' , 'HTTP/1.1' , 'HTTP/2' , 'HTTP/3'] as const


export type CloudFrontLogPayload = {
  /** Precise floating-point Unix Epoch Timestamp (e.g., 1787984000.123) */
  timestamp: number;
  
  /** The total elapsed time taken to respond in seconds, down to the millisecond */
  time_taken: number;
  
  /** The 3-digit numeric HTTP response code returned to the client */
  sc_status: number;
  
  /** The domain name that the client used to access your asset */
  ctx_host: string;
  
  /** The standardized HTTP request method utilized */
  cs_method: typeof methods[number];
  
  /** The path to the specific asset being requested */
  cs_uri_stem: string;
  
  /** The portion of the URL following the '?' character. Returns '-' if empty */
  cs_uri_query: string;
  
  /** How the edge server handled the request relative to its local cache */
  x_edge_result_type: typeof edgeResultTypes[number];
  
  /** A unique, encrypted string token identifier generated by CloudFront for tracing */
  x_edge_request_id: string;
  
  /** The specific cryptographic protocol version used to secure the connection */
  ssl_protocol: typeof sslProtocols[number];
  
  /** The exact mathematical encryption algorithm cipher suite utilized */
  ssl_cipher: string;
  
  /** The cache classification status that CloudFront sent back to the viewer */
  x_edge_response_result_type: typeof edgeResultTypes[number];
  
  /** Text string identifying the client's browser engine, device, and OS */
  cs_user_agent: string;
  
  /** The URL of the previous web page that linked the user to this asset */
  cs_referer: string;
  
  /** Name-value cookie string parameters included in the request headers */
  cs_cookie: string;
  
  /** The exact total number of bytes served to the client, headers included */
  sc_bytes: number;
  
  /** The total number of bytes received from the client */
  cs_bytes: number;
  
  /** The specific AWS edge server facility code handling the request (e.g., 'LHR5') */
  x_edge_location: string;
  
  /** The file size in bytes declared in the response payload content-length header */
  sc_content_len: number;
  
  /** Speed of initial response: time between receiving a request and sending the first byte */
  time_to_first_byte: number;
  
  /** The strict value found inside the client's HTTP Host header string */
  cs_host_header: string;
  
  /** The underlying transfer protocol web scheme used */
  cs_protocol: typeof userProtocols[number];
  
  /** The exact version of the HTTP engine utilized by the client connection */
  cs_protocol_version: typeof userProtocolVersion[number];
  
  /** Tracks the processing state if executing Field-Level Encryption */
  fle_status: string;
  
  /** The actual running count of individual body fields encrypted by CloudFront */
  fle_encrypted_fields: number;
  
}

function createOrderObj(displayText: string, objKey: keyof CloudFrontLogPayload){
	return {
		displayText: displayText,
		objKey: objKey
	}
}

export const columnOrder = [
  // Time and location
 createOrderObj("Datetime", "timestamp"),
 createOrderObj("Edge Location", "x_edge_location"),
  // Cliet details
 createOrderObj("User Agent", "cs_user_agent"),
  // Request attributes
 createOrderObj("Host Domain", "ctx_host"),
 createOrderObj("Host Domain Header", "cs_host_header"),
 createOrderObj("URL Path", "cs_uri_stem"),
 createOrderObj("URL Query String", "cs_uri_query"),
  // Response
 createOrderObj("HTTP Method", "cs_method"),
 createOrderObj("Cookie Header", "cs_cookie"),
 createOrderObj("Referrer URL", "cs_referer"),
 createOrderObj("HTTP Status Code", "sc_status"),
 createOrderObj("Response Content Length", "sc_content_len"),
 createOrderObj("Bytes Sent", "sc_bytes"),
 createOrderObj("Bytes Received", "cs_bytes"),
  // CDN
 createOrderObj("Edge Cache Result Type", "x_edge_result_type"),
 createOrderObj("Edge Response Result Type", "x_edge_response_result_type"),
 createOrderObj("Edge Request ID", "x_edge_request_id"),
 createOrderObj("Time Taken (Seconds)", "time_taken"),
 createOrderObj("Time to First Byte (Seconds)", "time_to_first_byte"),
  // Security
 createOrderObj("Protocol Used", "cs_protocol"),
 createOrderObj("HTTP Protocol Version", "cs_protocol_version"),
 createOrderObj("SSL Protocol Version", "ssl_protocol"),
 createOrderObj("SSL Cipher Suite", "ssl_cipher"),
 createOrderObj("Field-Level Encryption Status", "fle_status"),
 createOrderObj("Field-Level Encryption Count", "fle_encrypted_fields")
]

/**
 * SSE Event containing an actual CloudFront log entry.
 */
type LogEntryEvent = {
  /** Unique identifier for the SSE message event. */
  id?: string;
  /** The type of event being sent. */
  event: 'log_entry';
  /** The log data payload. */
  data: CloudFrontLogPayload;
}

/**
 * SSE Event used to keep the connection alive (Heartbeat).
 */
type PingEvent = {
  id?: string;
  event: 'ping';
  /** Ping events typically have an empty string or timestamp as data. */
  data: string;
}

/**
 * The unified event type received from the CloudFront log stream.
 */
export type CloudFrontLogEvent = LogEntryEvent | PingEvent;

export type DisplayLogEvent = Required<CloudFrontLogEvent>
