name: Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  AWS_Provision:
    runs-on: ubuntu-latest

    name: aws_provision

    permissions:
      id-token: write
      contents: write
    
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::111644099040:role/sherlihyDotCom-prod-iam
          aws-region: us-east-1

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: AWS user creds
        run: |
          mkdir ~/.aws
          echo -e "[sherlihyDotCom-prod]\n" > ~/.aws/credentials
          echo -e "aws_access_key_id = ${{secrets.AWS_ACCESS_KEY_ID}}\n" >> ~/.aws/credentials
          echo -e "aws_secret_access_key = ${{secrets.AWS_SECRET_ACCESS_KEY}}\n" >> ~/.aws/credentials

      - name: Deploy changes
        run: npm run launch_prod

      - name: Push tf state
        run: |
          git config --global user.name 'SHerlihy'
          git config --global user.email 'steven_herlihy@yahoo.com'

      - name: Add main state
        run: git add -f deployment/production/terraform.tfstate

      - name: Add sub state
        run: git add -f deployment/production/**/terraform.tfstate

      - name: Add var files
        run: git add -f deployment/production/**/vars.tfvars

      - name: Commit
        run: git commit -q -n -m"Auto updating tf state" > /dev/null 2>&1 || true

      - name: Push
        run: git push
