name: Deploy

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

env:
  HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
  HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
  HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
  HCP_ORGANIZATION_ID: ${{ secrets.HCP_ORGANIZATION_ID }}
  HCP_BUCKET_NAME: "sherlihy-dot-com"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  AWS_Provision:
    runs-on: ubuntu-latest

    name: aws_provision

    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::111644099040:role/sherlihy-dot-com
          aws-region: eu-west-2

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      #      - name: Image Build
      #        run: npm run image

      #      - name: Tf deploy
      #        run: npm run deploy-prod
      #
      #      - uses: actions/upload-artifact@v4
      #        with:
      #          name: sherlihyDotCom_prod-state
      #          path: |
      #            ../../deployment/production/terraform.tfstate
      #            ../../deployment/production/main.tf
      #            ../../deployment/production/variables.tf
      #          retention-days: 5
      #
      #      - uses: actions/download-artifact@v4
      #        with:
      #          name: sherlihyDotCom_prod-state
      #          path: /tmp/actions_artifacts
      #
      #      - name: Update local tf
      #        run: npm run update-tf-state

      - name: Setup demo image deploy
        run: npm run setup-demo-deploy

      #      - uses: actions/upload-artifact@v4
      #        with:
      #          name: demo_image-state
      #          path: |
      #            deployment/imaging/demo_instance/main.tf
      #            deployment/imaging/demo_instance/terraform.tfstate
      #          retention-days: 1
      #
      #      - uses: actions/download-artifact@v4
      #        with:
      #          name: demo_image-state
      #          path: /tmp/actions_artifacts
      #
      #      - name: Dl artifacts
      #        run: ls -a /tmp/actions_artifacts
      #
      #      - name: Move in Deploy State
      #        run: mv -f /tmp/actions_artifacts/* deployment/imaging/demo_instance

      - name: Is Moved In?
        run: ls -a deployment/imaging/demo_instance

      - name: stage tf state
        run: git add -f deployment/imaging/demo_instance/terraform.tfstate

      - name: commit changed files
        run: |
          git config --global user.name 'SHerlihy'
          git config --global user.email 'steven_herlihy@yahoo.com'
          git commit -m "Auto updating tf state"
          git remote set-url --push origin https://SHerlihy:$GITHUB_TOKEN@github.com/sherlihy-dot-com
          git push

          # git fetch origin main
          # git push origin HEAD:main

      #      - name: Update demo image tf
      #        run: npm run update-demo-img-tf
      #
      #      - name: Deploy demo image
      #        run: npm run deploy-demo-image
